[package]
name = "julian"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
lexopt = "0.3.0"
thiserror = "1.0.40"

[dev-dependencies]
rstest = { version = "0.17.0", default-features = false }
rstest_reuse = "0.5.0"
